### PR TITLE
Support dotted pairs

### PR DESCRIPTION
**Pull request by plexus**
Follow-up to #4 , let's see if Travis is happy now.

### CODE REVIEW

**Comment by bbatsov** [comment]
Nicely done! I'm thinking we should also start a changelog and mention this there, so it's easier to track such improvements.

**Comment by plexus** [comment]
Do you have an example of how you manage a changelog in elisp projects? Given that we don't really do releases of these libs (melpa just pulls master) I wouldn't really know how to structure this.

**Comment by bbatsov** [comment]
Well, that's not completely true as we have a 0.1 release. :-) (otherwise people using only `MELPA Stable` can't use the library) In general it makes sense to cut new releases every now and then, especially if it's something needed in `clojure-mode` or CIDER. 

That's a format I use in most of my projects - https://github.com/clojure-emacs/cider/blob/master/CHANGELOG.md

**Comment by plexus** [comment]
I added a CHANGELOG and tagged a v0.2.0 release.

**Comment by bbatsov** [comment]
Nice!

**Pull request merged**
